### PR TITLE
fix: DLT-2117 copy/paste on message input

### PR DESCRIPTION
**Pull request by juliodialpad**
# Fix copy/paste behavior on message input

## Obligatory GIF (super important!)

Obligatory GIF

## :hammer_and_wrench: Type Of Change

These types will increment the version number on release:

- [x] Fix

## :book: Jira Ticket

https://dialpad.atlassian.net/browse/DLT-2117

## :book: Description

Removed custom pasteHandler added on: https://github.com/dialpad/dialtone/pull/511 and subsequent prop added on: https://github.com/dialpad/dialtone/pull/543.

This custom pasteHandler was removing custom nodes while pasting (emojis, links, mentions, etc). We detected only emojis, but none of the mentioned nodes would work as we were obtaining the `text/plain` content of the clipboard.

## :bulb: Context

The custom behavior introduced was not needed as the issue was only on getting the input text, which can be configured to output `\n` character to solve the issue.

If we want to improve even more this behavior in the future, we could also find a way to just replace the hard breaks with soft breaks, but for now I think this fix will do.

## :pencil: Checklist

For all PRs:

- [x] I have ensured no private Dialpad links or info are in the code or pull request description (Dialtone is a public repo!).
- [x] I have reviewed my changes.
- [x] I have considered the performance impact of my change.

For all Vue changes:

- [x] I have made my changes in Vue 2 and Vue 3. Note: you may sync your changes from Vue 2 to Vue 3 (or vice versa) using the `./scripts/dialtone-vue-sync.sh` script. Read docs here: [Dialtone Vue Sync Script](../packages/dialtone-vue3/.github/CONTRIBUTING.md#dialtone-vue-sync-script)

## :crystal_ball: Next Steps

Test if this helps at all with https://dialpad.atlassian.net/browse/DP-116205

## :camera: Screenshots / GIFs

- Html output

html output

- Text output

text output

## :link: Sources

https://tiptap.dev/docs/editor/api/editor#gettext

### CODE REVIEW

**Comment by iropolo** [comment]
https://dialpad.atlassian.net/browse/DP-116205 issue still reproducible

**Review by iropolo — APPROVED** [review]
image

</br>


image

**Comment by ninamarina** [comment]
It's again converting the `<br>` to paragraphs 😢 

input

The emojis work again and also the links though. We could decide that this is a trade off, but we should consult with product.

**Comment by juliodialpad** [comment]
> It's again converting the `<br>` to paragraphs 😢
> 
> input
> 
> The emojis work again and also the links though. We could decide that this is a trade off, but we should consult with product.

Yes, as I mentioned, we could find a way to replace all the hard breaks with soft ones. I can do a quick investigation, shouldn't be too hard.

**Comment by juliodialpad** [comment]
@ninamarina should be fixed now 😄

**Review by ninamarina — APPROVED** [review]
Works like charm ✨

**Pull request merged**
