### PR TITLE
feat(emoji-row, time-pill): feed time pill and emoji style updates

### PR DESCRIPTION
**Pull request by francisrupert**
# Feed time pill and emoji style updates

## :hammer_and_wrench: Type Of Change

These types will increment the version number on release:

- [ ] Fix
- [x] Feature
- [ ] Performance Improvement
- [ ] Refactor

## :book: Description

Pushing some spacing pixels, correct Design Token colors, yanno... picky stuff to strictly align to [intended design](https://www.figma.com/file/oTY56LgQha8ljb4c8w4GtO/Dialpad-App-Components?type=design&node-id=9481-26849&mode=design&t=PtqZSJB3IWdGiiWK-4).

## :pencil: Checklist

For all PRs:

- [x] I have ensured no private Dialpad links or info are in the code or pull request description (Dialtone is a public repo!).
- [x] I have reviewed my changes.
- [x] I have added all relevant documentation.
- [x] I have considered the performance impact of my change.

For all CSS changes:

- [x] I have used design tokens whenever possible.
- [x] I have considered how this change will behave on different screen sizes.
- [x] I have visually validated my change in light and dark mode.
- [x] I have used gap or flexbox properties for layout instead of margin whenever possible.

### CODE REVIEW

**Review by braddialpad — COMMENTED** [review]
Looks good, make sure the change on percy is what you intended (looks pretty good to me). And also you'll have to port this to vue 3. I can do this for you if there's no further changes you need to make.

**Comment by francisrupert** [comment]
> And also you'll have to port this to vue 3

I haven't done a Vue PR since the monorepo. [Same `.sh` steps apply](https://github.com/dialpad/dialtone/blob/08c68aae1f5f68f47cdad7239e748a06ee4e6ad9/packages/dialtone-vue3/.github/CONTRIBUTING.md?plain=1#L102-L105)?

**Comment by francisrupert** [comment]
@braddialpad, Thanks for the Vue 3 sync. I've approved in Percy too. Just need an approval and this'll be good to go.

**Comment by braddialpad** [comment]
> > And also you'll have to port this to vue 3
> 
> I haven't done a Vue PR since the monorepo. [Same `.sh` steps apply](https://github.com/dialpad/dialtone/blob/08c68aae1f5f68f47cdad7239e748a06ee4e6ad9/packages/dialtone-vue3/.github/CONTRIBUTING.md?plain=1#L102-L105)?

No it's a different script now that we switched to monorepo `./scripts/dialtone-vue-sync.sh` and it's not quite a straightforward as the old script.. Going to see if I can find a way to make this a bit easier because right now you've got to enter a bunch of git SHAs and such for it to work, so I did it for you here.

**Review by braddialpad — APPROVED** [review]
Looks great thanks

**Pull request merged**
