### PR TITLE
docs: DLT-1765 update favicon to Ai logomark

### PR DESCRIPTION
**Pull request by ninamarina**
# Update favicon to Ai logomark

## :hammer_and_wrench: Type Of Change

- [x] Documentation

## :book: Jira Ticket
[DLT-1765]

## :book: Description
Updates the svgs and pngs inside the folder `favicons`. This is working correctly for Chrome and Firefox, but it's not working for Safari, maybe I am missing something 🤔 
Also, added the new logo in "https://static.dialpadcdn.com/favicons/dialpad-favicon.svg", I didn't update the old favicon in case that is used by someone else and they want to keep the previous logo. I can overwrite If we are sure that the old logo is going to be deprecated.

## :camera: Screenshots / GIFs

Chrome:
image

[DLT-1765]: https://dialpad.atlassian.net/browse/DLT-1765?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by braddialpad — APPROVED** [review]
nice! guess we should update the logos on doc site / storybook too eh? (separate pr)

**Comment by iropolo** [comment]
hmm.. ye definetly sth change from safari cos it was working before 🤔 

dialpad/dialtone.dialpad/dialtone.dialpad-preview/

image

**Comment by iropolo** [comment]
Could you revert the safari one to see if it still works as expected in the deploy preview?, cos maybe it is sth related to the deploy-preview

**Comment by ninamarina** [comment]
> Could you revert the safari one to see if it still works as expected in the deploy preview?, cos maybe it is sth related to the deploy-preview



> Could you revert the safari one to see if it still works as expected in the deploy preview?, cos maybe it is sth related to the deploy-preview



> Could you revert the safari one to see if it still works as expected in the deploy preview?, cos maybe it is sth related to the deploy-preview

Locally I don't see it correct either: 

image

**Review by iropolo — APPROVED** [review]

**Pull request merged**
