### PR TITLE
fix: message input issues

### PR DESCRIPTION
**Pull request by juliodialpad**
# Fix message input issues

## Obligatory GIF (super important!)

Obligatory GIF

## :hammer_and_wrench: Type Of Change

These types will increment the version number on release:

- [x] Fix

## :book: Jira Ticket

https://dialpad.atlassian.net/browse/DLT-1586

## :book: Description

- Updated message input to remove scrollbar while adding an emoji
- Fixed the issues with copy/pasting emojis
- Changed default text on DtRichTextEditor to avoid issues with unicode

## :bulb: Context

Issues reported on message input

## :pencil: Checklist

For all PRs:

- [x] I have ensured no private Dialpad links or info are in the code or pull request description (Dialtone is a public repo!).
- [x] I have reviewed my changes.

For all Vue changes:

- [x] I have made my changes in Vue 2 and Vue 3. Note: you may sync your changes from Vue 2 to Vue 3 (or vice versa) using the `./scripts/dialtone-vue-sync.sh` script.

### CODE REVIEW

**Comment by ninamarina** [comment]
I get this when pressing focus test (both Vue 2 and Vue 3):
image

**Review by iropolo — APPROVED** [review]
Thanks,
Regarding what Nina says, yes, I remember reporting it in some PR, I don't remember the answer but seems that it wasn't removed yet.

**Comment by juliodialpad** [comment]
> Thanks, Regarding what Nina says, yes, I remember reporting it in some PR, I don't remember the answer but seems that it wasn't removed yet.

Should I remove it?

**Comment by juliodialpad** [comment]
Removed focus test button

**Comment by iropolo** [comment]
> Removed focus test button

Thanks, yes I guess it was a leftover.

**Pull request merged**
