### PR TITLE
feat: DLT-1627 adding new tokens for expressive mode

### PR DESCRIPTION
**Pull request by yorbi-dp**
# feat: DLT-1627 adding new tokens for expressive mode

- Medium / Default (Desktop) version mode
- Small (Mobile) version mode
- Typography level only

## Obligatory GIF (super important!)

Obligatory GIF

## :hammer_and_wrench: Type Of Change

These types will increment the version number on release:

- [ ] Fix
- [x] Feature
- [ ] Performance Improvement
- [ ] Refactor

These types will not increment the version number, but will still deploy to documentation site on release:

- [ ] Documentation
- [ ] Build system
- [ ] CI
- [ ] Style (code style changes, not css changes)
- [ ] Test
- [ ] Other (chore)

## :book: Jira Ticket

https://dialpad.atlassian.net/browse/DLT-1627

## :book: Description

Create Typography tokens for Expressive mode, including default (desktop) and small (mobile) versions.

## :bulb: Context

From now on, the MKT team will be using DT in their process. However, one thing changes from our current set: the Font Family and Font sizes. We are keeping the same structure and naming convention for these cases but creating a new mode.

## :pencil: Checklist

For all PRs:

- [x] I have ensured no private Dialpad links or info are in the code or pull request description (Dialtone is a public repo!).
- [x] I have reviewed my changes.
- [x] I have added all relevant documentation.
- [x] I have considered the performance impact of my change.

For all CSS changes:

- [ ] I have used design tokens whenever possible.
- [x] I have considered how this change will behave on different screen sizes.
- [x] I have visually validated my change in light and dark mode.
- [ ] I have used gap or flexbox properties for layout instead of margin whenever possible.

## :crystal_ball: Next Steps

Double check out-put and how to use it.

### CODE REVIEW

**Comment by ninamarina** [comment]
The generated files look good:
image

The styles are not in `dialtone.css`, because we are only adding light and dark themes, will that go in another PR?

**Review by iropolo — APPROVED** [review]

**Comment by braddialpad** [comment]
> The styles are not in `dialtone.css`, because we are only adding light and dark themes, will that go in another PR?

Yeah I think it should. We should do this part rather than yorbi since it's dealing with Post CSS and such.

**Review by braddialpad — APPROVED** [review]

**Comment by yorbi-dp** [comment]
Proof of current output:
Screenshot 2024-04-11 at 3 05 33 PM

----

> Yeah I think it should. We should do this part rather than yorbi since it's dealing with Post CSS and such.

Does this need to be a new Jira ticket? @braddialpad

**Comment by braddialpad** [comment]
> Does this need to be a new Jira ticket? @braddialpad

Yep https://dialpad.atlassian.net/browse/DLT-1696

**Pull request merged**
