### PR TITLE
feat(icon): DLT-1760 add rocket icon

### PR DESCRIPTION
**Pull request by fede-dp**
# feat: DLT-1760 Add new icon Rocket

## Obligatory GIF (super important!)

Obligatory GIF

## :hammer_and_wrench: Type Of Change

These types will increment the version number on release:

- [x] Fix
- [ ] Feature
- [ ] Performance Improvement
- [ ] Refactor

These types will not increment the version number, but will still deploy to documentation site on release:

- [ ] Documentation
- [ ] Build system
- [ ] CI
- [ ] Style (code style changes, not css changes)
- [ ] Test
- [ ] Other (chore)

## :book: Jira Ticket

https://dialpad.atlassian.net/browse/DLT-1760

## :book: Description

added new icon requested by designers, Rocket.
## :pencil: Checklist

For all PRs:

- [x] I have ensured no private Dialpad links or info are in the code or pull request description (Dialtone is a public repo!).
- [x] I have reviewed my changes.
- [x] I have added all relevant documentation.
- [x] I have considered the performance impact of my change.

## :camera: Screenshots / GIFs

image

### CODE REVIEW

**Comment by francisrupert** [comment]
Add keywords, how about `launch`, `release`, `boost`, `space`, `speed`, `future`, `start`.

**Comment by fede-dp** [comment]
> Add keywords, how about `launch`, `release`, `boost`, `space`, `speed`, `future`, `start`.

I think the keywords file didn't update but i already did that, will push again with that!

**Review by iropolo — APPROVED** [review]

**Review by francisrupert — APPROVED** [review]
🚀

**Review by braddialpad — COMMENTED** [review]
🚀

**Pull request merged**
