### PR TITLE
fix(select-menu): corrected selectmenu's icon color in dark mode

### PR DESCRIPTION
**Pull request by francisrupert**
# PR Title

Corrected selectmenu's icon color in dark mode

## :hammer_and_wrench: Type Of Change

- [x] Fix
- [ ] Feature
- [ ] Performance Improvement
- [ ] Refactor

## :pencil: Checklist

For all CSS changes:

- [ ] I have used design tokens whenever possible.
- [x] I have considered how this change will behave on different screen sizes.
- [x] I have visually validated my change in light and dark mode.
- [ ] I have used gap or flexbox properties for layout instead of margin whenever possible.

## :camera: Screenshots / GIFs

image

### CODE REVIEW

**Comment by francisrupert** [comment]
NOTE: this still isn't an ideal method. Ultimately a DT Icon should be placed inline instead of the current embedded base64 image. And using `.dialtone-theme-dark * {}` may not scale well in the long-run.

**Comment by braddialpad** [comment]
> using `.dialtone-theme-dark * {}` may not scale well in the long-run.

Yeah we will likely have to change this fairly soon for web components, not to mention multidimensional themes.

> this still isn't an ideal method. Ultimately a DT Icon should be placed inline instead of the current embedded base64 image

Can we just do this now? we have the icon: "chevrons-up-down"

**Comment by francisrupert** [comment]
> > using `.dialtone-theme-dark * {}` may not scale well in the long-run.
> 
> Yeah we will likely have to change this fairly soon for web components, not to mention multidimensional themes.
> 
> > this still isn't an ideal method. Ultimately a DT Icon should be placed inline instead of the current embedded base64 image
> 
> Can we just do this now? we have the icon: "chevrons-up-down"

Breaking change right? Just searching DP and DPM codebases there quite a few instances of using the raw HTML of `.d-select` and those would need to be updated.

Updating the Vue component to use DTIcon is of course easy enough. Perhaps do so after this temporary quick update and put in backlog?

**Comment by braddialpad** [comment]
> Breaking change right? Just searching DP and DPM codebases there quite a few instances of using the raw HTML of `.d-select` and those would need to be updated.

Yeah right, I was just thinking we could do this in the vue component and it wouldn't be a breaking change.

> Perhaps do so after this temporary quick update and put in backlog?

Yep sounds good

**Review by braddialpad — APPROVED** [review]

**Pull request merged**
