### PR TITLE
fix(message-input): DLT-1937 set input focus area correctly

### PR DESCRIPTION
**Pull request by braddialpad**
# fix(message-input): DLT-1937 set input focus area correctly

## Obligatory GIF (super important!)

Obligatory GIF

## :hammer_and_wrench: Type Of Change

These types will increment the version number on release:

- [x] Fix

## :book: Jira Ticket

https://dialpad.atlassian.net/browse/DLT-1937

## :book: Description

Couple of fixes for message input

1. focus the input when any area of the message input container is clicked rather than just the text input
2. allow drag/drop on any area of the message input container rather than just the text input
3. shift + enter was setting paragraphs instead of line breaks. Updated to set line breaks

## :bulb: Context

Some quick fixes requested by messaging team from above mentioned Jira ticket.

## :pencil: Checklist

For all PRs:

- [x] I have ensured no private Dialpad links or info are in the code or pull request description (Dialtone is a public repo!).
- [x] I have reviewed my changes.
- [x] I have added all relevant documentation.
- [x] I have considered the performance impact of my change.

For all Vue changes:

- [x] I have made my changes in Vue 2 and Vue 3. Note: you may sync your changes from Vue 2 to Vue 3 (or vice versa) using the `./scripts/dialtone-vue-sync.sh` script. Read docs here: [Dialtone Vue Sync Script](../packages/dialtone-vue3/.github/CONTRIBUTING.md#dialtone-vue-sync-script)

## :crystal_ball: Next Steps

Let messaging team know when this is released so they can try it out

## :link: Sources

https://tiptap.dev/docs/editor/extensions/nodes/hard-break

### CODE REVIEW

**Review by bianca-artola-dialpad — COMMENTED** [review]
Thanks for fixing these issues Brad! The fixes are working well 😄. 
I have seen some complaints about the copy&paste mentions feature. Do you think this is something we can easily fix, or would it be better to keep it as a separate issue?

https://github.com/user-attachments/assets/3bdcbe60-5039-41d5-9031-290346a36856

**Comment by braddialpad** [comment]
> Do you think this is something we can easily fix, or would it be better to keep it as a separate issue?

Maybe, I'll take a look, see if it's a quick fix.

**Comment by braddialpad** [comment]
@bianca-artola-dialpad copy paste issue has been fixed now as well

**Review by bianca-artola-dialpad — APPROVED** [review]
Okey this is really great 🥳 thank you Brad!
As part of this PR the following fixes seems to be resolved:

- https://dialpad.atlassian.net/browse/DLT-1937
- https://dialpad.atlassian.net/browse/DLT-1895
- https://dialpad.atlassian.net/browse/DLT-1892
- https://dialpad.atlassian.net/browse/DP-107300
- https://dialpad.atlassian.net/browse/DLT-1956

Let's test this on firespotter 🤞🏽

**Comment by braddialpad** [comment]
@bianca-artola-dialpad I updated to latest version in ubervoice.

**Pull request merged**
