### PR TITLE
feat(logo): DLT-1802 color options

### PR DESCRIPTION
**Pull request by francisrupert**
# DP Logos available as themeable (via tokens), inverted, black, and white.

## :hammer_and_wrench: Type Of Change

These types will increment the version number on release:

- [ ] Fix
- [x] Feature
- [ ] Performance Improvement
- [ ] Refactor

## :book: Jira Ticket

https://dialpad.atlassian.net/browse/DLT-1802

## :book: Description

Logo assets currently assume light background and its color is limited to `color.foreground.primary`. Added...

- `inverted`
- `black`
- `white`

## :bulb: Context

* https://dialpad.atlassian.net/browse/DP-101208
* https://dialpad.com/app/messages/agxzfnViZXItdm9pY2VyGAsSC1RleHRNZXNzYWdlGICAhfLI_L8KDA

## :pencil: Checklist

For all PRs:

- [x] I have ensured no private Dialpad links or info are in the code or pull request description (Dialtone is a public repo!).
- [x] I have reviewed my changes.
- [x] I have added all relevant documentation.
- [x] I have considered the performance impact of my change.

### CODE REVIEW

**Review by iropolo — APPROVED** [review]
Looks good, thanks

**Review by braddialpad — APPROVED** [review]
Looks great, well documented, thanks

**Review by fede-dp — APPROVED** [review]

**Comment by francisrupert** [comment]
@ninamarina,

Great start. Let's use the following specific for the 4 cases:

* Default: no background color
* `{logo-name}-inverted`: containing bg is `color.surface.contrast`
* `{logo-name}-black`: containing bg is `color.neutral.white`
* `{logo-name}-white`: containing bg is `color.neutral.black`

**Comment by francisrupert** [comment]
Can you add a `gap` between all of them?

**Comment by francisrupert** [comment]
@ninamarina This is great! In fact, since you've managed to break them out separately would it be simple enough to move them to a new "Brand" page within the Design section? Screenshot attached is what I'm thinking (just me moving stuff around in Inspector).

As a bonus, this sets the stage for a more comprehensive "Brand" section. For now, just siloing the Brand assets there is the perfect MVP for this. 

image

**Comment by francisrupert** [comment]
Yesh, this is perfect! Related, though probably a new issue to log: navigating to the filtered icon page doesn't work. It only works on a full page load. 

https://github.com/dialpad/dialtone/assets/1165933/27ee7e24-91cf-4abe-b564-baa771e2979b

**Comment by braddialpad** [comment]
> Yesh, this is perfect! Related, though probably a new issue to log: navigating to the filtered icon page doesn't work. It only works on a full page load.

Should be a simple fix @ninamarina. Have to pass the router params a slightly different way

from the vue-router docs @ https://router.vuejs.org/guide/essentials/named-routes.html#Named-Routes

```
<router-link :to="{ name: 'profile', params: { username: 'erina' } }">
  User profile
</router-link>
```

**Comment by ninamarina** [comment]
> Yesh, this is perfect! Related, though probably a new issue to log: navigating to the filtered icon page doesn't work. It only works on a full page load.
> 
>  Screen.Recording.2024-06-12.at.9.41.31.AM.mov

I couldn't get this working here, but as a workaround I made the link open a new tab. That way it applies the filter when the page loads.

**Review by braddialpad — APPROVED** [review]

**Comment by francisrupert** [comment]
> ...workaround I made the link open a new tab...

Would replacing the `<router-link>` with a raw `<a>` effectively result in a refreshed target without spawning new window?

**Comment by ninamarina** [comment]
> > ...workaround I made the link open a new tab...
> 
> Would replacing the `<router-link>` with a raw `<a>` effectively result in a refreshed target without spawning new window?

it does! will change it for an `<a>` tag

**Comment by francisrupert** [comment]
Perfect. 🚀❗️

**Pull request merged**
