### PR TITLE
chore(docs): DLT-1879 new thumbnails for Scroller and Scrollbar

### PR DESCRIPTION
**Pull request by fede-dp**
# docs: DLT-1879 new thumbnails for Scroller and Scrollbar components in docsite

## Obligatory GIF (super important!)

Obligatory GIF

## :hammer_and_wrench: Type Of Change

These types will increment the version number on release:

- [x] Fix
- [ ] Feature
- [ ] Performance Improvement
- [ ] Refactor

These types will not increment the version number, but will still deploy to documentation site on release:

- [ ] Documentation
- [ ] Build system
- [ ] CI
- [ ] Style (code style changes, not css changes)
- [ ] Test
- [ ] Other (chore)

## :book: Jira Ticket

[DLT-1879](https://dialpad.atlassian.net/browse/DLT-1879)
## :book: Description
Replacing the image in scroller and fixing the one in scrollbar

## :pencil: Checklist

For all PRs:

- [x] I have ensured no private Dialpad links or info are in the code or pull request description (Dialtone is a public repo!).
- [x] I have reviewed my changes.
- [x] I have added all relevant documentation.
- [x] I have considered the performance impact of my change.

## :camera: Screenshots / GIFs

image

## :link: Sources

[DLT-1879]: https://dialpad.atlassian.net/browse/DLT-1879?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by fede-dp** [comment]
Looks good imho!
image

**Review by francisrupert — COMMENTED** [review]
I like it, distinguishes the two much better. Make sure they're using Design Tokens for colors. I think those were manually edited in the SVG, e.g. `var(--dt-color-surface-moderate)` and so on. View the other thumbnails SVG files for reference on likely CSS Variables to use. 

image

**Comment by fede-dp** [comment]
image
fixed! @francisrupert

**Review by francisrupert — APPROVED** [review]
🚀

**Pull request merged**
