### PR TITLE
fix(root-layout): focus ring on scrollable regions

### PR DESCRIPTION
**Pull request by braddialpad**
# fix(root-layout): focus ring on scrollable regions

## Obligatory GIF (super important!)

Obligatory GIF

## :hammer_and_wrench: Type Of Change

These types will increment the version number on release:

- [x] Fix

## :book: Description

Added inset focus ring on focus visible to sidebar and content sections

## :bulb: Context

By accessibility rules scrolling regions must be focusable, however our root layout component does not currently indicate focus. Added an inset focus ring on focus-visible. This gets cut off by the scrollbar if it is shown, however I cannot find any possible way to fix this due to the component taking up all available space with no padding / margin 🤷. This solution is still better than nothing

## :pencil: Checklist

For all PRs:

- [x] I have ensured no private Dialpad links or info are in the code or pull request description (Dialtone is a public repo!).
- [x] I have reviewed my changes.
- [x] I have added all relevant documentation.
- [x] I have considered the performance impact of my change.

For all CSS changes:

- [x] I have used design tokens whenever possible.

## :camera: Screenshots / GIFs

Screenshot 2024-02-28 at 12 14 54 PM

## :link: Sources

https://accessibilityinsights.io/info-examples/web/scrollable-region-focusable/

### CODE REVIEW

**Comment by juliodialpad** [comment]
Screenshot 2024-02-28 at 4 03 04 p m

It looks ok for me 🤔

**Comment by juliodialpad** [comment]
Screenshot 2024-02-28 at 4 04 11 p m

Even with the scrollbar it doesn't look too bad, but it's not the same as the screenshot you provided

**Comment by braddialpad** [comment]
> Even with the scrollbar it doesn't look too bad, but it's not the same as the screenshot you provided

Ah yeah it's the "Always show scrollbars" option on mac. I have this enabled so I notice bugs exactly like this, haha

**Comment by juliodialpad** [comment]
> > Even with the scrollbar it doesn't look too bad, but it's not the same as the screenshot you provided
> 
> Ah yeah it's the "Always show scrollbars" option on mac. I have this enabled so I notice bugs exactly like this, haha

Right, always forgot about that setting 😅

**Pull request merged**
