### PR TITLE
docs: update typography docsite table

### PR DESCRIPTION
**Pull request by juliodialpad**
Moved from https://github.com/dialpad/dialtone/pull/971

## Description
updating images → svg tokenized 
new table with text styles

## Pull Request Checklist

 - [ ] Ask the contributors if a similar effort is already in process or has been solved.
 - [ ] Review the [contribution guidelines](https://github.com/dialpad/dialtone/blob/staging/.github/CONTRIBUTING.md).
 - [ ] Use `staging` as your pull request's base branch. (All PRs using `production` as its base branch will be declined).
 - [ ] Ensure all `gulp` scripts successfully compile.
 - [ ] Update, remove, or extend all affected documentation.
 - [ ] Ensure no private Dialpad links or info are in the code or pull request description (Dialtone is a public repo!).

### CODE REVIEW

**Review by iropolo — APPROVED** [review]

**Comment by iropolo** [comment]
Approved to avoid blocking

**Comment by juliodialpad** [comment]
> Approved to avoid blocking

Forgot to put this PR into draft, this is still not finished and @fede-dp is on vacations I think, so don't review this, please.

**Comment by iropolo** [comment]
@fede-dp @yorbi-dp @francisrupert Ping to move forward or close this PR.

**Comment by fede-dp** [comment]
closing this pr because we prioritize the content over the development, we will take this later this Q.

**Pull request closed without merging**
