### PR TITLE
fix(docs): DLT-1994 use dialtone scrollbar in docsite

### PR DESCRIPTION
**Pull request by braddialpad**
# fix(docs): DLT-1994 use dialtone scrollbar in docsite

## Obligatory GIF (super important!)

Obligatory GIF

## :hammer_and_wrench: Type Of Change

These types will increment the version number on release:

- [x] Fix

## :book: Jira Ticket

https://dialpad.atlassian.net/browse/DLT-1994

## :book: Description

Update the main scrollbar of the docsite to use the new dialtone scrollbar. Could not use the directive because the vuepress scrollbar actually exists outside of the vue instance on the body, so just used overlayscrollbars directly.

Can probably update the leftbar as well, but I have one technical concern I want to discuss outside the scope of this PR.

## :bulb: Context

Mostly because this "jumping" problem annoys me.

## :pencil: Checklist

For all PRs:

- [x] I have ensured no private Dialpad links or info are in the code or pull request description (Dialtone is a public repo!).
- [x] I have reviewed my changes.
- [x] I have added all relevant documentation.
- [x] I have considered the performance impact of my change..

## :link: Sources

https://github.com/KingSora/OverlayScrollbars

### CODE REVIEW

**Comment by ninamarina** [comment]
In Firefox the scroll works correctly, but the scrollbar doesn't follow along:
firefox-scroll

**Review by ninamarina — CHANGES_REQUESTED** [review]
It's not working correctly in Firefox. In chrome is ok

**Comment by braddialpad** [comment]
Looks like they added support in version 2.3.0 for something called ScrollTimeline API, which firefox doesn't support. It seems like overlayscrollbars is only supposed to use it in supported browsers but that is clearly not working here. Downgrading to version 2.2.0, before this was implemented fixed the issue. I'll report a bug on their github.

https://github.com/KingSora/OverlayScrollbars/releases/tag/v2.3.0

**Comment by braddialpad** [comment]
Actually... seems to be silently fixed in 2.10.0, so just updated to that version.

**Review by francisrupert — APPROVED** [review]
> Mostly because this "jumping" problem annoys me.

Good man 😛

> Could not use the directive because the vuepress scrollbar actually exists outside of the vue instance on the body, so just used overlayscrollbars directly.

Does this imply we should make "use overlayscrollbars directly" an option in the documentation? 

Overall, this is highly satisfying to see. Since you and @ninamarina have implemented it several times, I wonder how much effort all of [DLT-1984 epic](https://dialpad.atlassian.net/browse/DLT-1984) would be.

> Can probably update the leftbar as well...

I'm assuming that'd be [DLT-1878, Root Layout](https://dialpad.atlassian.net/browse/DLT-1878)

**Review by ninamarina — APPROVED** [review]
Looks good, thanks!

**Comment by braddialpad** [comment]
> Does this imply we should make "use overlayscrollbars directly" an option in the documentation?

Yeah there could be some use cases for this, though it would be pretty rare currently. Created jira here: https://dialpad.atlassian.net/browse/DLT-1997

> I'm assuming that'd be [DLT-1878, Root Layout](https://dialpad.atlassian.net/browse/DLT-1878)

Yep

**Pull request merged**
