### PR TITLE
feat: added icons: task, add task and small view. added more keywords

### PR DESCRIPTION
**Pull request by yorbi-dp**
## Description
added new icons:
- task
- add task
- small self view
- poly-handset
- poly-base-station
- poly-adapter

added more keywords to existing icons.

## Pull Request Checklist

 - [x] Ask the contributors if a similar effort is already in process or has been solved.
 - [x] Review the [contribution guidelines](https://github.com/dialpad/dialtone/blob/staging/.github/CONTRIBUTING.md).
 - [x] Use `staging` as your pull request's base branch. (All PRs using `production` as its base branch will be declined).
 - [x] Ensure all `gulp` scripts successfully compile.
 - [x] Update, remove, or extend all affected documentation.
 - [x] Ensure no private Dialpad links or info are in the code or pull request description (Dialtone is a public repo!).

### CODE REVIEW

**Review by juliodialpad — APPROVED** [review]
Nice! Those keywords where missing long ago, thanks!

Congratulations on your first monorepo PR too

**Comment by juliodialpad** [comment]
You should include the vue 3 version changes here, but I'm working trying to unify the icons in just one version so don't worry for that now.

**Review by braddialpad — APPROVED** [review]
Nice keywords! looks good thanks.

**Comment by braddialpad** [comment]
> You should include the vue 3 version changes here, but I'm working trying to unify the icons in just one version so don't worry for that now.

Can we have two different package.jsons and folders due to different dependencies, but then it uses the icon library / json data from just one folder?

**Review by iropolo — APPROVED** [review]
Thanks!!

**Comment by yorbi-dp** [comment]
Just included the Vue3 version and some new icons we received today!

**Comment by juliodialpad** [comment]
Merged branch with a breaking change I did on #8, should be good to go, just give it a small review and check that the work did is all there. @yorbi-dp

**Pull request merged**
