### PR TITLE
fix(icon): DLT-1784 flatten icons with multiple paths into single path

### PR DESCRIPTION
**Pull request by fede-dp**
# [DLT-1784] Fixing multiple icons into one path trace

## Obligatory GIF (super important!)

Obligatory GIF

## :hammer_and_wrench: Type Of Change

These types will increment the version number on release:

- [x] Fix
- [ ] Feature
- [ ] Performance Improvement
- [ ] Refactor

These types will not increment the version number, but will still deploy to documentation site on release:

- [ ] Documentation
- [ ] Build system
- [ ] CI
- [ ] Style (code style changes, not css changes)
- [ ] Test
- [ ] Other (chore)

## :book: Jira Ticket

[DLT-1784](https://dialpad.atlassian.net/browse/DLT-1784)

## :book: Description
Fixing a lot of icons we currently have as multi-paths in the SVG we export form Figma and wasn't right

## :pencil: Checklist

For all PRs:

- [x] I have ensured no private Dialpad links or info are in the code or pull request description (Dialtone is a public repo!).
- [x] I have reviewed my changes.
- [x] I have added all relevant documentation.
- [x] I have considered the performance impact of my change.

[DLT-1784]: https://dialpad.atlassian.net/browse/DLT-1784?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DLT-1784]: https://dialpad.atlassian.net/browse/DLT-1784?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by francisrupert** [comment]
Still lots of icons with overlapping `<path>`s. I tested this on https://dialtone.dialpad.com/deploy-previews/pr-442/design/icons/ by changing foreground color to muted foreground color. 

A few problems here:

1. This is a lot of tedious work to do manually, and I apologize for that since we put ourselves in this position when we adopted Feather Icons in a slightly different way.
2. My instinct previously was for a build script to flatten all `<path>` elements into a single one (I think @juliodialpad did some kind of icon build script for `currentColor`). However... that wouldn't solve for Figma since this same task solves for both. I wonder if there's a Figma plugin or way to do that.

image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image

**Comment by francisrupert** [comment]
image
image
image

**Comment by francisrupert** [comment]
> 2\. My instinct previously was for a build script to flatten all `<path>` elements into a single one (I think @juliodialpad did some kind of icon build script for `currentColor`). However... that wouldn't solve for Figma since this same task solves for both. I wonder if there's a Figma plugin or way to do that.

Did you look into this? This is not a good process to be done **_manually_**. I'm still seeing lots of icons with multiple `<path>` elements (attached video). Since this task started out purely for those icons that glaringly have overlapping elements, I'd say you should log a followup task to figure the best way in Figma to resolve this — presumably a Figma Plugin (Icon Toolbox and Icon Genie are two I found but haven't tried). 

https://github.com/user-attachments/assets/a5317cc2-9dcd-4f44-855a-3965765004c6

**Comment by fede-dp** [comment]
Oh, I thought it was something to check with @juliodialpad in the future, I'm finishing this task and creating a new one to investigate that, thanks francis!

**Comment by francisrupert** [comment]
Doing a build step isn't a bad idea, but this problem persists in Figma. For example, when a designer changes the icon within a Button it results in multiple colors since it's expecting a single `vector` layer. So solving this in Figma solves it for the exported SVG (though you will have to mass replace them all again, so tedious).

**Comment by fede-dp** [comment]
Created [DLT-2003](https://dialpad.atlassian.net/browse/DLT-2003) to address the automation/solution for good, do you think we should discard this one or we can merge it while we solve the problem? @francisrupert 

[DLT-2003]: https://dialpad.atlassian.net/browse/DLT-2003?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by francisrupert** [comment]
> ...do you think we should discard this one or we can merge it while we solve the problem?

This PR is still worth completing and publishing since it will resolve some current very glaring issues — for both the SVGs and Figma Icon Library. Be sure to publish the Icon Library too to coincide with this PR.

**Review by francisrupert — APPROVED** [review]
Approving so you can close this out as [DLT-1784](https://dialpad.atlassian.net/browse/DLT-1784) is currently defined. Any further work should be in [DLT-2003](https://dialpad.atlassian.net/browse/DLT-2003).

**Pull request merged**
