### PR TITLE
refactor(badge, emoji-tabset, empty-state): remove DtIcon

### PR DESCRIPTION
**Pull request by juliodialpad**
# Remove DtIcon usage on Badge, Emoji Tabset and Empty State components

## Obligatory GIF (super important!)

Obligatory GIF

## :hammer_and_wrench: Type Of Change

These types will increment the version number on release:

- [x] Refactor

## :book: Jira Ticket

https://dialpad.atlassian.net/browse/DLT-1916

## :book: Description

- Removed DtIcon usage from Badge, Emoji tabset and Empty state components, changed to slots if any icon could be used or to specific icon if just a few needed for the component.

## :bulb: Context

We're making dialtone-vue fully tree-shakeable

## :pencil: Checklist

For all PRs:

- [x] I have ensured no private Dialpad links or info are in the code or pull request description (Dialtone is a public repo!).
- [x] I have reviewed my changes.
- [x] I have considered the performance impact of my change.

For all Vue changes:

- [x] I have added / updated unit tests.
- [x] I have made my changes in Vue 2 and Vue 3. Note: you may sync your changes from Vue 2 to Vue 3 (or vice versa) using the `./scripts/dialtone-vue-sync.sh` script. Read docs here: [Dialtone Vue Sync Script](../packages/dialtone-vue3/.github/CONTRIBUTING.md#dialtone-vue-sync-script)

## :crystal_ball: Next Steps

- Merge to beta and test

### CODE REVIEW

**Comment by ninamarina** [comment]
Some tests are failing. Seems like importing the icons this way it doesn't add the `data-qa` attribute that it used to.

**Comment by ninamarina** [comment]
The controls in storybook are still showing a select menu even though now the icon and illustration are slots: 
image

Same with the badge

**Comment by ninamarina** [comment]
> The controls in storybook are still showing a select menu even though now the icon and illustration are slots: image
> 
> Same with the badge

Never mind, I see that's on purpose just for the playground

**Comment by ninamarina** [comment]
We have a new property "iconSize" for the badge component. Do we really want that? What would happen if a different size is passed? I don't see any changes in storybook
image

**Review by ninamarina — APPROVED** [review]
Looks good, I only have the question about the iconSize prop.

**Comment by braddialpad** [comment]
> We have a new property "iconSize" for the badge component. Do we really want that? What would happen if a different size is passed? I don't see any changes in storybook

Wouldn't they just pass the size of the icon via the component they pass into the slot? Don't think the prop is necessary. Should we instead have a scoped slot for default size?

**Comment by juliodialpad** [comment]
You're right, I was thinking on making "easier" to handle both icon sizes with a default size of '200' but makes no sense to have a prop, will remove it.

**Review by braddialpad — CHANGES_REQUESTED** [review]
The changes look pretty good to me, however we will need to update the docsite examples to reflect the new changes.

**Review by braddialpad — APPROVED** [review]
Looks good, you can merge this. Regarding the doc I mentioned you can do it in another PR if you wish.

**Comment by juliodialpad** [comment]
> Looks good, you can merge this. Regarding the doc I mentioned you can do it in another PR if you wish.

Updated docs, don't want to forgot to do it later haha

**Review by braddialpad — APPROVED** [review]
Thanks!

**Pull request merged**
