### PR TITLE
feat(icons): thumbs up and down filled icons

### PR DESCRIPTION
**Pull request by fede-dp**
# New filled thumbs up and down icon

Obligatory GIF

## 🛠️ Type Of Change
These types will increment the version number on release:

- [ ] Fix
- [x] Feature
- [ ] Performance Improvement
- [ ] Refactor

## 📖 Jira Ticket
https://dialpad.atlassian.net/browse/DLT-1541

## 📖 Description

Create `thumbs-up-filled` and `thumbs-down-filled`, counterparts to [thumbs-up](https://dialtone.dialpad.com/design/icons/?icon_name=thumbs-up) and [thumbs-down](https://dialtone.dialpad.com/design/icons/?icon_name=thumbs-down).

## 📝 Checklist

- [x] I have ensured no private Dialpad links or info are in the code or pull request description (Dialtone is a public repo!).
- [x] I have reviewed my changes.
- [x] I have added all relevant documentation.
- [x] I have considered the performance impact of my change.

### CODE REVIEW

**Review by francisrupert — CHANGES_REQUESTED** [review]
Seems to only have just the `up` icon, missing `down`. Ensure that the two icons that Marshall did yesterday are the source.

**Comment by francisrupert** [comment]
I changed the subject for proper commit naming convention, e.g. `feat(icons): ...` and corrected the description's markdown formatting.

**Review by iropolo — APPROVED** [review]
Looks good, thanks!

**Review by francisrupert — COMMENTED** [review]
@fede-dp  I made [these last comments directly](https://github.com/dialpad/dialtone/commit/fbe2b39e6eeb1cd9a5f520de1454e0c44978d94a) on the commit, so they didn't appear in the conversation.

**Review by francisrupert — APPROVED** [review]
awesome! merge away

**Pull request merged**
