### PR TITLE
feat: DLT-1762 dialpad logo updated

### PR DESCRIPTION
**Pull request by fede-dp**
# DLT-1762 - dialpad logo updated

## Obligatory GIF (super important!)

Obligatory GIF

## :hammer_and_wrench: Type Of Change

These types will increment the version number on release:

- [ ] Fix
- [x] Feature
- [ ] Performance Improvement
- [ ] Refactor

These types will not increment the version number, but will still deploy to documentation site on release:

- [ ] Documentation
- [ ] Build system
- [ ] CI
- [ ] Style (code style changes, not css changes)
- [ ] Test
- [ ] Other (chore)

## :book: Jira Ticket

https://dialpad.atlassian.net/browse/DLT-1762
## :book: Description
adding a new spot illustration used by the branding/marketing team

## :pencil: Checklist

For all PRs:

- [x] I have ensured no private Dialpad links or info are in the code or pull request description (Dialtone is a public repo!).
- [x] I have reviewed my changes.
- [x] I have added all relevant documentation.
- [x] I have considered the performance impact of my change.

## :camera: Screenshots / GIFs

Screenshot 2024-05-23 at 4 21 59 PM

### CODE REVIEW

**Comment by braddialpad** [comment]
This appears to be mostly empty state documentation updates, but the title is dialpad logo updated. Is this intentional?

**Comment by fede-dp** [comment]
woops sorry about that, got mixed up with the branches and changes lol @braddialpad fixed!

**Comment by iropolo** [comment]
These are the expected?

image
image
image

image
image
image

**Comment by iropolo** [comment]
No keywords or category. It is intended?

**Review by braddialpad — CHANGES_REQUESTED** [review]
Shows up in the vue component, but not under illustrations on the docsite:

Screenshot 2024-05-24 at 11 18 45 AM

**Comment by iropolo** [comment]
Then we will use the icon for 

dialpad-ai-color-reversed
image

dialpad-ai-reversed
image

**Comment by fede-dp** [comment]
I tried my best to add the new images to the docsite adding it to `svg-spot.json` and doesn't seems to be working, not sure what i'm doing wrong, that's the only think we need to get done to ship this 😭  @braddialpad @iropolo

**Comment by braddialpad** [comment]
Hmm 1 sec I'll check it out

**Comment by braddialpad** [comment]
Man something is really screwed up here, lol. Will check again on monday.

**Comment by braddialpad** [comment]
We've still got a number of problems here.

These illustrations are not changing in dark mode like they were before:

Screenshot 2024-06-03 at 8 57 18 PM

This one is not being scaled down to the size of the box. You can see the color differences here as well:

before:

Screenshot 2024-06-03 at 8 59 55 PM

after:
Screenshot 2024-06-03 at 8 58 35 PM

**Comment by iropolo** [comment]
> We've still got a number of problems here.
> 
> These illustrations are not changing in dark mode like they were before:
> 

Did they react to dark mode before? 🤔 @fede-dp 


> This one is not being scaled down to the size of the box. You can see the color differences here as well:

Lemme see, probably the css class `dialtone-icon-card__icon--autosize` specific for this section.

**Comment by braddialpad** [comment]
> Did they react to dark mode before? 🤔 @fede-dp

They actually did, you can see on https://dialtone.dialpad.com/design/illustrations/ seems like the white changes to black.

**Comment by iropolo** [comment]
> > Did they react to dark mode before? 🤔 @fede-dp
> 
> They actually did, you can see on https://dialtone.dialpad.com/design/illustrations/ seems like the white changes to black.

Ohh... I check this one
https://dialtone.dialpad.com/vue/index.html?path=/story/components-illustration--default&args=name:blank-space

**Comment by iropolo** [comment]
K, yes thats happens because we are working with differents SVG, 

previous on `@dialpad/dialtone-css/lib/dist/svg/spot`
current on `@dialpad/dialtone-icons/dist/svg/illustrations/`

**Comment by iropolo** [comment]
Seems like the ones in `packages/dialtone-icons/src/svg/illustrations` are wrong, I replaced one and it seems to work.
I will update them.

image

image

**Comment by iropolo** [comment]
Okay cool, seems like it is working now everywhere.

**Comment by iropolo** [comment]
ping @fede-dp

**Review by braddialpad — APPROVED** [review]
Nice, looks great now! Thanks @iropolo

**Pull request merged**
