### PR TITLE
feat(emoji-picker): DP-113112 add shift key info on selected-emoji event

### PR DESCRIPTION
**Pull request by bianca-artola-dialpad**
# add(emoji-picker): DP-113112 add shift key info on selected-emoji event

## Obligatory GIF (super important!)

Obligatory GIF

## :hammer_and_wrench: Type Of Change

These types will increment the version number on release:

- [x] Feature

## :book: Jira Ticket
https://dialpad.atlassian.net/browse/DP-113112

## :book: Description
This pull request enhances the selected-emoji event by including information about key events. With this update, we can now identify whether an emoji was selected using the Shift + Enter keys.

## :bulb: Context
For going into GA with the new message input component, we need to allow users to add an emoji to the input field with Shift + Enter without closing the emoji picker. To enable this functionality on the product side, it's essential to detect when an emoji is selected using the Shift + Enter key combination.

### CODE REVIEW

**Comment by bianca-artola-dialpad** [comment]
Firespotter changes: https://github.com/dialpad/firespotter/pull/48999

**Comment by ninamarina** [comment]
Looks good! Do you also need it to add the shiftKey info on click? You would have to add it also to the click event in that case

**Comment by braddialpad** [comment]
> Looks good! Do you also need it to add the shiftKey info on click? You would have to add it also to the click event in that case

Yes I think we would also need this.

**Comment by bianca-artola-dialpad** [comment]
> Looks good! Do you also need it to add the shiftKey info on click? You would have to add it also to the click event in that case

good catch, should be working now. thank you!

**Review by ninamarina — APPROVED** [review]

**Review by braddialpad — APPROVED** [review]
Great!

**Pull request merged**
