### PR TITLE
fix(tabs): fix inverted boolean storybook

### PR DESCRIPTION
**Pull request by iropolo**
## Description
Fix inverted prop on storybook controller to work as a boolean

Update:
Fixed a couple component with non-working boolean storybook controller

### CODE REVIEW

**Review by francisrupert — COMMENTED** [review]
That did it, though need to apply to the others, e.g. `borderless`, `disabled`. 
image

For that matter, ensure this isn't occurring in other Components' controls.

**Review by braddialpad — APPROVED** [review]
Pretty silly this is not the default in storybook... Probably a vue specific thing.

**Comment by iropolo** [comment]
I will check out all the components on vue2 to confirm boolean value are correct.

**Comment by iropolo** [comment]
I fixed all boolean controls I found that need to be fixed in our components (vue2). Will require review, thanks

**Comment by iropolo** [comment]
Removed `no-visual-test` and added `visual-test-ready` label to trigger percy check.

**Pull request merged**
