### PR TITLE
feat(message-input): DLT-1753 add support for dpm meeting pill

### PR DESCRIPTION
**Pull request by braddialpad**
# feat(message-input): DLT-1753 add support for dpm meeting pill

## Obligatory GIF (super important!)

Obligatory GIF

## :hammer_and_wrench: Type Of Change

These types will increment the version number on release:

- [x] Feature

## :book: Jira Ticket

https://dialpad.atlassian.net/browse/DLT-1753

## :book: Description

- Added a new node view to support the functionality of DPM pill within the message input.
- Refactored rich-text-editor to use `$listeners` so we don't have to manually output events from node-views in rich-text-editor itself. Clicking the button on the pill will trigger meeting-pill-close event.
- Still need to do vue 3 changes. It will be a bit of additional work because of `$listeners`.

## :bulb: Context

Since this component is quite product specific I've included it within message input recipe instead of rich text editor, and made a way to pass additional extensions to the rich-text-editor.

In order to get this to show up you need to set the value to <meeting-pill text="Start a meeting"/> into the input (with i18n wrapped text in product of course). It will output the pill in the text as "/dpm"

The component will not invoke this immediately when typing /dpm, you have to receive the selected-command event and then set the input to display the node view as mentioned above.

There is some bug with the input losing focus right now, it's not related to this change, I am going to look into it.

## :pencil: Checklist

For all PRs:

- [x] I have ensured no private Dialpad links or info are in the code or pull request description (Dialtone is a public repo!).
- [x] I have reviewed my changes.
- [x] I have added all relevant documentation.
- [x] I have considered the performance impact of my change.

For all Vue changes:

- [ ] I have added / updated unit tests.
- [ ] I have made my changes in Vue 2 and Vue 3. Note: you may sync your changes from Vue 2 to Vue 3 (or vice versa) using the `./scripts/dialtone-vue-sync.sh` script. Read docs here: [Dialtone Vue Sync Script](../packages/dialtone-vue3/.github/CONTRIBUTING.md#dialtone-vue-sync-script)
- [ ] I have validated components with a screen reader.
- [ ] I have validated components keyboard navigation.

For all CSS changes:

- [x] I have used design tokens whenever possible.
- [x] I have considered how this change will behave on different screen sizes.
- [x] I have visually validated my change in light and dark mode.
- [x] I have used gap or flexbox properties for layout instead of margin whenever possible.

## :crystal_ball: Next Steps

Let Bianca know to try it out in product when this is released.

## :camera: Screenshots / GIFs

Screenshot 2024-06-12 at 12 15 43 PM

## :link: Sources

https://tiptap.dev/docs/editor/guide/node-views/vue

### CODE REVIEW

**Comment by ninamarina** [comment]
How will this be used by the product? Would they need to add the meeting pill as an additional extension? In that case, does it need to be exported?

**Comment by braddialpad** [comment]
> How will this be used by the product? Would they need to add the meeting pill as an additional extension? In that case, does it need to be exported?

No, it's just automatically used in the message_input (but not rich_text_editor)

**Review by bianca-artola-dialpad — COMMENTED** [review]
qq: is there a way to disable typing when having the meeting pill? 
image

**Comment by braddialpad** [comment]
> qq: is there a way to disable typing when having the meeting pill?

hmm not really without also disabling the backspace to remove functionality. I will try and find a solution.

**Comment by braddialpad** [comment]
> qq: is there a way to disable typing when having the meeting pill?

Added new prop called "preventTyping" that will prevent you from typing any more characters when true, but will still allow you to delete.

**Comment by bianca-artola-dialpad** [comment]
> > qq: is there a way to disable typing when having the meeting pill?
> 
> Added new prop called "preventTyping" that will prevent you from typing any more characters when true, but will still allow you to delete.

Okay then on product side we will update `preventTyping` prop on `onSelectedCommand` function and will update the value of the input to whatever we need. Sounds good! I think we should be good with that on our side 👍🏽 
btw I'm not seeing `preventTyping` prop [here](https://dialtone.dialpad.com/vue/deploy-previews/pr-363/?path=/docs/recipes-conversation-view-message-input--docs)

**Review by ninamarina — APPROVED** [review]

**Comment by braddialpad** [comment]
> btw I'm not seeing `preventTyping` prop [here](https://dialtone.dialpad.com/vue/deploy-previews/pr-363/?path=/docs/recipes-conversation-view-message-input--docs)

Right, I need to add it to message input also

**Pull request merged**
